version: '3.7'
services:
  web:
    build:
      context: .
    command: ./entrypoint.sh
    volumes:
      -  .:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - rabbitmq
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - rabbitmq
  rabbit:
    image: rabbitmq:3.10.7-management-alpine
    restart: on-failure
    container_name: rabbit
    hostname: rabbit
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      - rabbitmq
  celery:
    build:
      context: .
    command: ./celery-entrypoint.sh
    depends_on:
      - db
      - rabbit
      - web
    restart: on-failure
    networks:
      - rabbitmq
  # flower for celery
  flower:
    build:
      context: .
    ports:
      - "5566:5566"
    command: celery -A core flower  --address=0.0.0.0 --port=5566
    networks:
      - rabbitmq
    depends_on:
      - celery

volumes:
  postgres_data:
networks:
  rabbitmq:
    external: true
