version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data: