version: '3.7'
services:
  web:
    build:
      context: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      -  .:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data: