# Generated by Django 4.0.5 on 2022-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='blocked until:'),
        ),
    ]
