# Generated by Django 4.0.5 on 2022-06-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_blocked_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='blocked'),
        ),
    ]
